DROP TABLE TEREN CASCADE CONSTRAINTS;
DROP TABLE CONSTRUCTIE CASCADE CONSTRAINTS;
DROP TABLE INFO_CONSTRUCTIE CASCADE CONSTRAINTS;

-- CREARE TABELE
CREATE TABLE TEREN(
ID_TEREN NUMBER CONSTRAINT PK_TID PRIMARY KEY,
TIP_TEREN VARCHAR2(9) CONSTRAINT CK_TTIP CHECK (TIP_TEREN IN('ASFALT','IARBA','PIETRIS','INTRARE')), --MANDATORY CONCRETE, GRASS, GRAVEL
NUME_TEREN VARCHAR2(50) CONSTRAINT NN_NUMET NOT NULL, --POATE SA FIE CAMPING, PARCARE, SAU PERIMETRUL FESTIVALULUI (IMPARTIT IN ZONE IN FUNCTIE DE TIPUL DE TEREN)
FORMA_TEREN SDO_GEOMETRY
);

CREATE TABLE CONSTRUCTIE(
ID_CONSTRUCTIE NUMBER CONSTRAINT PK_CONST PRIMARY KEY,
COD_CONSTRUCTIE NUMBER CONSTRAINT NN_CODC NOT NULL, -- COD INFORMATIV PENTRU MAP VIEW
FORMA_CONSTRUCTIE SDO_GEOMETRY
);

CREATE TABLE INFO_CONSTRUCTIE(
ID_INFO_CONST NUMBER CONSTRAINT PK_ICONST PRIMARY KEY,
ID_CONSTRUCTIE REFERENCES CONSTRUCTIE(ID_CONSTRUCTIE),
TIP_CONSTRUCTIE VARCHAR2(100) CONSTRAINT CK_CTIP CHECK(TIP_CONSTRUCTIE IN('TOALETA','CORT MANCARE','CORT MERCH','SCENA', 'BAR','PRIM AJUTOR', 'BIROU INFORMATII','ZONA MESE')), 
-- BIROU INFORMATII (COD 1), CORT MANCARE (COD 2), BARURI (COD 3), PRIM AJUTOR (COD 4), CORT MERCH (COD 5), TOALETE (COD 6),MESE (COD 7), SCENA (COD 8)
NUME_FIRMA VARCHAR2(100) CONSTRAINT NN_NUMEF NOT NULL,
CAPACITATE NUMBER
);

--INSERT PENTRU TERENURI

INSERT INTO TEREN VALUES(
    1,
    'INTRARE',
    'INTRARE VIZITATORI',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(4,1, 9,4)
    )
);

INSERT INTO TEREN VALUES(
    2,
    'ASFALT',
    'TEREN RECREERE SCENE 1 SI 2',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,1),
    SDO_ORDINATE_ARRAY(4,4, 16,4, 21,9, 21,12, 4,12, 4,4)
    )
);

INSERT INTO TEREN VALUES(
    3,
    'PIETRIS',
    'ZONA SCENE 1 SI 2',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(4,12, 21,17)
    )
);

INSERT INTO TEREN VALUES(
    4,
    'ASFALT',
    'ZONA TRANSFER SCENA 3',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,1),
    SDO_ORDINATE_ARRAY(4,17, 6,17, 13,22, 13,35, 10,35, 10,25, 4,22, 4,17)
    )
);

INSERT INTO TEREN VALUES(
    5,
    'IARBA',
    'ZONA SCENA 3',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(4,32, 10,41)
    )
);

INSERT INTO TEREN VALUES(
    6,
    'ASFALT',
    'TEREN RECREERE SCENA 3',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(10,35, 15,41)
    )
);

INSERT INTO TEREN VALUES(
    7,
    'INTRARE',
    'INTRARE TRUPE',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(12,17, 15,19)
    )
);


INSERT INTO TEREN VALUES(
    8,
    'IARBA',
    'ZONA CAMPING',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(25,18, 35,34)
    )
);

INSERT INTO TEREN VALUES(
    9,
    'ASFALT',
    'PARCARE MASINI',
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(25,8, 35,18)
    )
);
SELECT * FROM TEREN;

INSERT INTO user_sdo_geom_metadata
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
  VALUES (
  'teren',
  'forma_teren',
  SDO_DIM_ARRAY(   
    SDO_DIM_ELEMENT('X', 0, 50, 0.005),
    SDO_DIM_ELEMENT('Y', 0, 50, 0.005)
     ),
  NULL  
);

INSERT INTO CONSTRUCTIE VALUES(
    1,
    1,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(8,2, 9,4)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- birou informatii intrare
    1,
    1,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(8,2, 9,4)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- mancare scene 1 si 2
    2,
    2,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,1),
    SDO_ORDINATE_ARRAY(15,5, 16,5, 20,9, 19,9, 15,5)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- mancare transfer scene
    3,
    2,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(10,25, 11,30)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- baruri scenele 1 si 2
    4,
    3,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(19,10, 20,14)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- baruri pasaj scene
    5,
    3,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,1),
    SDO_ORDINATE_ARRAY(10,20, 12,21, 11,22, 9,21, 10,20)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- baruri scena 3
    6,
    3,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(10,40, 14,41)
    )
);

INSERT INTO CONSTRUCTIE VALUES( --prim ajutor
    7,
    4,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(18,15, 20,17)
    )
);


INSERT INTO CONSTRUCTIE VALUES( -- merch trupe scene 1 si 2
    8,
    5,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(10,4, 14,5)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- merch trupe scena 3
    9,
    5,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,1),
    SDO_ORDINATE_ARRAY(7,18, 10,20, 9,21, 6,19, 7,18)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- toalete scene 1 si 2
    10,
    6,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(4,7, 6,10)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- toalete scena 3
    11,
    6,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(13,35, 15,36)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- mese scene 1 si 2
    12,
    7,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,1),
    SDO_ORDINATE_ARRAY(12,7, 14,7, 18,11, 16,11, 12,7)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- mese pasaj
    13,
    7,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,1),
    SDO_ORDINATE_ARRAY(5,21, 11,24, 10,25, 4,22, 5,21)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- mese teren 3
    14,
    7,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(4,37, 6,41)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- scena 1
    15,
    8,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(7,14, 12,17)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- scena 2
    16,
    8,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(12,14, 17,17)
    )
);

INSERT INTO CONSTRUCTIE VALUES( -- scena 3
    17,
    8,
    SDO_GEOMETRY(
    2003,
    NULL,
    NULL,
    SDO_ELEM_INFO_ARRAY(1,1003,3),
    SDO_ORDINATE_ARRAY(5,32, 10,34)
    )
);



